version: '2'
services:
    app:
        image: mceddy/smartdisplay-server:latest
        environment:
            MQTT_SERVER: 'mqtt://localhost:1883'
            MQTT_USERNAME: 'user'
            MQTT_PASSWORD: 'password'
            LOCALE: 'de'
            PRIMARY_COLOR: '#00C8C8'
            SECONDARY_COLOR: '#4CFF00'
            TZ: 'Europe/Berlin'
            APP_CITY_WEATHER_CITY_ID: '2950159' # Berlin
            APP_CITY_WEATHER_APP_ID: 'your OpenWeather API key'
            APP_CITY_WEATHER_UNITS: 'metric'
            APP_CITY_WEATHER_MAX_CACHE_AGE: 30
            APP_ITERATIONS: 8
        restart: unless-stopped
